apiVersion: pipelinesascode.tekton.dev/v1alpha1
kind: Repository
metadata:
  annotations:
    appstudio.openshift.io/application: service-registry
    appstudio.openshift.io/component: apicurio-registry-1swl
    build.appstudio.openshift.io/build: "true"
    build.appstudio.openshift.io/type: build
    build.appstudio.openshift.io/version: "0.1"
    pipelines.appstudio.openshift.io/type: build
  creationTimestamp: null
  name: apicurio-registry-1swl
  namespace: burrzinga-tenant
spec:
  url: https://github.com/burrzinga/apicurio-registry
