apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: apicurio-registry-1swl
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: apicurio-registry-1swl
    app.kubernetes.io/part-of: service-registry
  name: apicurio-registry-1swl
  namespace: burrzinga-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: apicurio-registry-1swl
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: apicurio-registry-1swl
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:b4b1c9d0a8eda8830b027caa81decf794def165a3b2add4e977b04b670ee9ff7
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8081
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8081
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
