apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: apicurio-registry-1swl
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: apicurio-registry-1swl
    app.kubernetes.io/part-of: service-registry
  name: apicurio-registry-1swl
  namespace: burrzinga-tenant
spec:
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: apicurio-registry-1swl
    weight: 100
status: {}
