apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: apicurio-registry-1swl
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: apicurio-registry-1swl
    app.kubernetes.io/part-of: service-registry
  name: apicurio-registry-1swl
  namespace: burrzinga-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: apicurio-registry-1swl
status:
  loadBalancer: {}
